### ISSUE TITLE
v2.0.2 Mistakenly thinks mac is m1

### ISSUE THREAD

**Issue by MarcelWilson** [shadowmoose/selenium_drivers#12]
I have a macbook pro 2018 (intel) but pyderman 2.0.2 always attempts to download the m1 version of chromedriver.  

```
Downloading from:  https://chromedriver.storage.googleapis.com/95.0.4638.54/chromedriver_mac64_m1.zip
To:  /Users/me/tests/lib/chromedriver_95.0.4638.54.zip
```

Digging into the code a little, I noticed this in `__init__.py`
```
if _current_os == 'mac' and int(platform.release().split('.')[0]) >= 20:
	_current_os = 'mac-sur'
```
`platform.release()` for my machine returns `'21.1.0'`  don't know much about the platform versions, but I'm guessing this value needs to be adjusted.

<img width="259" alt="Screen Shot 2021-11-02 at 5 56 24 PM" src="https://user-images.githubusercontent.com/87030014/139963052-d216ef51-1751-4d7e-b041-28ac164ed627.png">

**Comment by shadowmoose** [comment]
Thanks for the report. I'd like to fix this, but I don't own a mac, so checking versions is difficult. I'm tagging this for anybody who is more familiar with the current state of the OS who wants to come along and assist, or at least offer me some guidance on versioning.

**Comment by eggplants** [comment]
`py-cpuinfo` is useful:

```python
# In my MacBook Pro:
cpuinfo.get_cpu_info().get("brand_raw")
>>> 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz'

# In M1 MacBook:
cpuinfo.get_cpu_info().get("brand_raw")
>>> 'Apple M1 Pro'
```

It seems to [execute](https://github.com/workhorsy/py-cpuinfo/blob/4d6987e5c30f2ebacb20781892c01329042cce60/cpuinfo/cpuinfo.py#L250-L252) `sysctl machdep.cpu` and [extract](https://github.com/workhorsy/py-cpuinfo/blob/4d6987e5c30f2ebacb20781892c01329042cce60/cpuinfo/cpuinfo.py#L620-L642) `machdep.cpu.brand_string` row.

**Comment by shadowmoose** [comment]
Interesting, and good to know. I'm not sure that relying on the brand string is reliable enough, but it might be a better solution.

**Comment by eggplants** [comment]
With only built-in packages:

```python
import platform, shutil, subprocess

def is_m1() -> bool:
    return (
        platform.system().lower() == "darwin" and
        shutil.which("sysctl") and
        subprocess.check_output(
            ["sysctl", "-n", "machdep.cpu.brand_string"]
        ).decode("utf-8").lower().startswith("apple m1")
    )
```

I'll make pr soon.
