### ISSUE TITLE
Edge was stopped distributing for mac?

### ISSUE THREAD

**Issue by eggplants** [shadowmoose/selenium_drivers#16]
I found tests for mac were failed in the latest commit.
https://github.com/shadowmoose/pyderman/actions/runs/2218801028

This is because the latest version (`102.0.1236.0`, beta channel) of EdgeDriver does not distribute a build for mac. Was it terminated up to `102.0.1235.0`? Or is it simply that the Mac version is not yet available to the public?

**Comment by shadowmoose** [comment]
Interesting, I'm unsure why they wouldn't have a build for the latest release, but it's pretty annoying that this is the case.

**Comment by shadowmoose** [comment]
This appears to have been resolved by their release, so I'm going to close this for now.
